sed -i -s s/yellow/#FFF231/ highlight.vim
sed -i -s s/lime/#99D02B/ highlight.vim
sed -i -s s/green/#33A65E/ highlight.vim
sed -i -s s/teal/#1AA18E/ highlight.vim
sed -i -s s/aqua/#1D86AE/ highlight.vim
sed -i -s s/blue/#386CB0/ highlight.vim
sed -i -s s/grape/#6964AD/ highlight.vim
sed -i -s s/violet/#A45AAA/ highlight.vim
sed -i -s s/ruby/#DF4C94/ highlight.vim
sed -i -s s/red/#F9344C/ highlight.vim
sed -i -s s/sunset/#FC4E32/ highlight.vim
sed -i -s s/orange/#FF9914/ highlight.vim
